In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\Y.PHANI MANJUNATH\\Downloads\\Dataset .csv")
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [3]:
inputs=df.drop(['Restaurant ID','Restaurant Name','Address','Locality','Locality Verbose','Is delivering now','Switch to order menu'
                ,'Rating color', 'Rating text','Aggregate rating','City'],axis='columns')
inputs.head()

,Country Code,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Price range,Votes
0,162,121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,3,314
1,162,121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,3,591
2,162,121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,4,270
3,162,121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,4,365
4,162,121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,4,229

In [4]:
from sklearn.preprocessing import LabelEncoder
letb=LabelEncoder()
leod=LabelEncoder()
lec=LabelEncoder()

In [5]:
inputs['Has Table booking']=letb.fit_transform(inputs['Has Table booking'])
inputs['Has Online delivery']=leod.fit_transform(inputs['Has Online delivery'])
inputs['Currency']=lec.fit_transform(inputs['Currency'])

In [6]:
inputs

,Country Code,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Price range,Votes
0,162,121.027535,14.565443,"French, Japanese, Desserts",1100,0,1,0,3,314
1,162,121.014101,14.553708,Japanese,1200,0,1,0,3,591
2,162,121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,0,1,0,4,270
3,162,121.056475,14.585318,"Japanese, Sushi",1500,0,0,0,4,365
4,162,121.057508,14.584450,"Japanese, Korean",1500,0,1,0,4,229
...,...,...,...,...,...,...,...,...,...,...
9546,208,28.977392,41.022793,Turkish,80,11,0,0,3,788
9547,208,29.041297,41.009847,"World Cuisine, Patisserie, Cafe",105,11,0,0,3,1034
9548,208,29.034640,41.055817,"Italian, World Cuisine",170,11,0,0,4,661
9549,208,29.036019,41.057979,Restaurant Cafe,120,11,0,0,4,901
9550,208,29.026016,40.984776,Cafe,55,11,0,0,2,591

In [7]:
inputs['Cuisines']=inputs['Cuisines'].fillna('Other')

In [8]:
inputs['Cuisines_list'] = inputs['Cuisines'].str.split(',').apply(lambda x: [c.strip() for c in x])

In [9]:
inputs.columns.tolist()

['Country Code',
 'Longitude',
 'Latitude',
 'Cuisines',
 'Average Cost for two',
 'Currency',
 'Has Table booking',
 'Has Online delivery',
 'Price range',
 'Votes',
 'Cuisines_list']

In [10]:
inputs.head()

,Country Code,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Price range,Votes,Cuisines_list
0,162,121.027535,14.565443,"French, Japanese, Desserts",1100,0,1,0,3,314,"[French, Japanese, Desserts]"
1,162,121.014101,14.553708,Japanese,1200,0,1,0,3,591,[Japanese]
2,162,121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,0,1,0,4,270,"[Seafood, Asian, Filipino, Indian]"
3,162,121.056475,14.585318,"Japanese, Sushi",1500,0,0,0,4,365,"[Japanese, Sushi]"
4,162,121.057508,14.584450,"Japanese, Korean",1500,0,1,0,4,229,"[Japanese, Korean]"

In [11]:
inputs['Primary_Cuisine'] = inputs['Cuisines_list'].apply(lambda x: x[0] if len(x) > 0 else 'Other')

In [12]:
inputs.head()

,Country Code,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Price range,Votes,Cuisines_list,Primary_Cuisine
0,162,121.027535,14.565443,"French, Japanese, Desserts",1100,0,1,0,3,314,"[French, Japanese, Desserts]",French
1,162,121.014101,14.553708,Japanese,1200,0,1,0,3,591,[Japanese],Japanese
2,162,121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,0,1,0,4,270,"[Seafood, Asian, Filipino, Indian]",Seafood
3,162,121.056475,14.585318,"Japanese, Sushi",1500,0,0,0,4,365,"[Japanese, Sushi]",Japanese
4,162,121.057508,14.584450,"Japanese, Korean",1500,0,1,0,4,229,"[Japanese, Korean]",Japanese

In [13]:
inputs.Primary_Cuisine.nunique()

120

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
inputs['Primary_Cuisine']=le.fit_transform(inputs['Primary_Cuisine'])

In [15]:
inputs.head(20)

,Country Code,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Price range,Votes,Cuisines_list,Primary_Cuisine
0,162,121.027535,14.565443,"French, Japanese, Desserts",1100,0,1,0,3,314,"[French, Japanese, Desserts]",39
1,162,121.014101,14.553708,Japanese,1200,0,1,0,3,591,[Japanese],55
2,162,121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,0,1,0,4,270,"[Seafood, Asian, Filipino, Indian]",98
3,162,121.056475,14.585318,"Japanese, Sushi",1500,0,0,0,4,365,"[Japanese, Sushi]",55
4,162,121.057508,14.584450,"Japanese, Korean",1500,0,1,0,4,229,"[Japanese, Korean]",55
5,162,121.056314,14.583764,Chinese,1000,0,0,0,3,336,[Chinese],27
6,162,120.979667,14.531333,"Asian, European",2000,0,1,0,4,520,"[Asian, European]",6
7,162,120.979333,14.540000,"Seafood, Filipino, Asian, European",2000,0,1,0,4,677,"[Seafood, Filipino, Asian, European]",98
8,162,120.980090,14.552990,"European, Asian, Indian",6000,0,1,0,4,621,"[European, Asian, Indian]",35
9,162,121.056532,14.572041,Filipino,1100,0,1,0,3,532,[Filipino],37
10,162,121.057916,14.567689,"Filipino, Mexican",800,0,0,0,3,1070,"[Filipino, Mexican]",37
11,162,121.060820,14.570849,"American, Ice Cream, Desserts",900,0,1,0,3,488,"[American, Ice Cream, Desserts]",2
12,162,121.075419,14.649503,"Filipino, Mexican",800,0,0,0,3,294,"[Filipino, Mexican]",37
13,162,121.033592,14.593450,Filipino,1000,0,1,0,3,458,[Filipino],37
14,162,121.038110,14.598890,Korean,700,0,0,0,3,223,[Korean],61
15,162,121.057040,14.237082,"Cafe, American, Italian, Filipino",800,0,0,0,3,29,"[Cafe, American, Italian, Filipino]",23
16,162,121.056587,14.237679,"Italian, Pizza",850,0,0,0,3,72,"[Italian, Pizza]",54
17,162,120.951589,14.101834,Filipino,1200,0,1,0,3,211,[Filipino],37
18,162,121.045878,14.554360,"Cafe, Korean, Desserts",600,0,0,0,2,118,"[Cafe, Korean, Desserts]",23
19,162,121.046220,14.549337,"Cafe, Bakery, American, Italian",1500,0,1,0,4,392,"[Cafe, Bakery, American, Italian]",23

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
cols_to_scale = ['Longitude', 'Latitude', 'Average Cost for two', 'Votes']
inputs[cols_to_scale] = scaler.fit_transform(inputs[cols_to_scale])

In [17]:
inputs.head(10)

,Country Code,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Price range,Votes,Cuisines_list,Primary_Cuisine
0,162,0.838318,0.574426,"French, Japanese, Desserts",0.001375,0,1,0,3,0.028718,"[French, Japanese, Desserts]",39
1,162,0.838278,0.574305,Japanese,0.001500,0,1,0,3,0.054052,[Japanese],55
2,162,0.838406,0.574590,"Seafood, Asian, Filipino, Indian",0.005000,0,1,0,4,0.024694,"[Seafood, Asian, Filipino, Indian]",98
3,162,0.838405,0.574630,"Japanese, Sushi",0.001875,0,0,0,4,0.033382,"[Japanese, Sushi]",55
4,162,0.838408,0.574621,"Japanese, Korean",0.001875,0,1,0,4,0.020944,"[Japanese, Korean]",55
5,162,0.838405,0.574614,Chinese,0.001250,0,0,0,3,0.030730,[Chinese],27
6,162,0.838174,0.574075,"Asian, European",0.002500,0,1,0,4,0.047558,"[Asian, European]",6
7,162,0.838173,0.574164,"Seafood, Filipino, Asian, European",0.002500,0,1,0,4,0.061917,"[Seafood, Filipino, Asian, European]",98
8,162,0.838176,0.574298,"European, Asian, Indian",0.007500,0,1,0,4,0.056795,"[European, Asian, Indian]",35
9,162,0.838405,0.574493,Filipino,0.001375,0,1,0,3,0.048656,[Filipino],37

In [18]:
y=inputs['Primary_Cuisine']
x=inputs.drop(['Cuisines','Cuisines_list','Primary_Cuisine'],axis='columns')

In [19]:
x.head()

,Country Code,Longitude,Latitude,Average Cost for two,Currency,Has Table booking,Has Online delivery,Price range,Votes
0,162,0.838318,0.574426,0.001375,0,1,0,3,0.028718
1,162,0.838278,0.574305,0.001500,0,1,0,3,0.054052
2,162,0.838406,0.574590,0.005000,0,1,0,4,0.024694
3,162,0.838405,0.574630,0.001875,0,0,0,4,0.033382
4,162,0.838408,0.574621,0.001875,0,1,0,4,0.020944

In [20]:
y.head()

0    39
1    55
2    98
3    55
4    55
Name: Primary_Cuisine, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [22]:
len(x_train)

7640

In [23]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=300,class_weight='balanced')
model.fit(x_train,y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=300)

In [24]:
y_pred=model.predict(x_test)

In [25]:
y_pred

array([79, 79, 79, ..., 12, 79, 68])

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)

Accuracy: 0.29304029304029305
Precision: 0.2411439932204063
Recall: 0.29304029304029305

C:\Users\Y.PHANI MANJUNATH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Y.PHANI MANJUNATH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))